build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18
labels:
  org.opencontainers.image.title: "RAG API"
  org.opencontainers.image.description: "RAG API deployment for Home Assistant."
  org.opencontainers.image.source: "https://github.com/bobbyquantum/addon-rag_api"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  PYTHON_VERSION: "3.11"
  RAG_API_VERSION: "v0.2.0" 
