# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: RAG API
version: "0.3.0-12"
slug: rag_api
description: RAG API for LibreChat Add-on
url: "https://github.com/BobbyQuantum/addon-librechat/tree/main/rag_api"
arch:
  - aarch64
  - amd64
init: false
apparmor: false
map:
  - share:rw
  - addon_config:rw
ports:
  3085/tcp: 3085
image: "ghcr.io/bobbyquantum/{arch}-addon-rag_api"
