# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base:9.0.5
  amd64: ghcr.io/hassio-addons/ubuntu-base:9.0.5
labels:
  org.opencontainers.image.title: "LibreChat"
  org.opencontainers.image.description: "LibreChat deployment for Home Assistant."
  org.opencontainers.image.source: "https://github.com/BobbyQuantum/addon-librechat"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  MONGODB_VERSION: "7.0"
  NVM_VERSION: "v0.39.3"
  NODE_VERSION: "v20.13.1"
  LIBRECHAT_VERSION: "v0.7.2"
  MEILISEARCH_VERSION: "v1.8.0"
