# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: LibreChat
version: "0.7.2-alpha3"
slug: librechat
description: LibreChat
url: "https://github.com/BobbyQuantum/addon-librechat/tree/main/librechat"
arch:
  - aarch64
  - amd64
init: false
apparmor: false
#host_network: false
ingress: true
ingress_port: 3080
ingress_entry: /
map:
  - share:rw
options:
  core_librechat_debug_logging: false
  core_domain_server: http://localhost:3080
  ai_openai_enabled: true
  ai_openai_key: user_provided
ports:
  3080/tcp: 3080
  # 27017/tcp: 27017
schema:
  core_librechat_debug_logging: "bool"
  core_domain_server: "str?"
  ai_openai_enabled: "bool"
  ai_openai_key: "str?"
image: "ghcr.io/bobbyquantum/{arch}-addon-librechat"
